In [57]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier

from sklearn.metrics import (
    f1_score,
    precision_score,
    recall_score,
    confusion_matrix,
    precision_recall_curve,
    classification_report,
)

In [58]:
train_df = pd.read_csv("../data/processed/train_features.csv")
test_df = pd.read_csv("../data/processed/test_features.csv")

# Ensure date is datetime
train_df["date"] = pd.to_datetime(train_df["date"])
test_df["date"] = pd.to_datetime(test_df["date"])

# Quick check
print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)

print("\nTrain columns sample:")
print(train_df.columns[:10].tolist())

Train shape: (1692, 170)
Test shape: (564, 169)

Train columns sample:
['date', '5cm_soil_moist', 'mean_dew_point_temp', 'max_temp', 'sea_level_pressure', 'sst_cameroon_mean_temperature_deg_c', 'sst_cameroon_mean_temperature_uncertainty', 'sst_indian_ocean_mean_temperature_deg_c', 'sst_indian_ocean_mean_temperature_uncertainty', 'potential_water_deficit']

In [59]:
train_df.head(5)

,date,5cm_soil_moist,mean_dew_point_temp,max_temp,sea_level_pressure,sst_cameroon_mean_temperature_deg_c,sst_cameroon_mean_temperature_uncertainty,sst_indian_ocean_mean_temperature_deg_c,sst_indian_ocean_mean_temperature_uncertainty,potential_water_deficit,2m_temp,u10,vapor_pressure_deficit,dryspell_warn_7d,year,month,season_year,5cm_soil_moist_rollmean_7,5cm_soil_moist_rollmin_7,5cm_soil_moist_rollmax_7,5cm_soil_moist_rollmean_14,5cm_soil_moist_rollmin_14,5cm_soil_moist_rollmax_14,5cm_soil_moist_rollmean_30,5cm_soil_moist_rollmin_30,5cm_soil_moist_rollmax_30,mean_dew_point_temp_rollmean_7,mean_dew_point_temp_rollmin_7,mean_dew_point_temp_rollmax_7,mean_dew_point_temp_rollmean_14,mean_dew_point_temp_rollmin_14,mean_dew_point_temp_rollmax_14,mean_dew_point_temp_rollmean_30,mean_dew_point_temp_rollmin_30,mean_dew_point_temp_rollmax_30,max_temp_rollmean_7,max_temp_rollmin_7,max_temp_rollmax_7,max_temp_rollmean_14,max_temp_rollmin_14,max_temp_rollmax_14,max_temp_rollmean_30,max_temp_rollmin_30,max_temp_rollmax_30,sea_level_pressure_rollmean_7,sea_level_pressure_rollmin_7,sea_level_pressure_rollmax_7,sea_level_pressure_rollmean_14,sea_level_pressure_rollmin_14,sea_level_pressure_rollmax_14,sea_level_pressure_rollmean_30,sea_level_pressure_rollmin_30,sea_level_pressure_rollmax_30,sst_cameroon_mean_temperature_deg_c_rollmean_7,sst_cameroon_mean_temperature_deg_c_rollmin_7,sst_cameroon_mean_temperature_deg_c_rollmax_7,sst_cameroon_mean_temperature_deg_c_rollmean_14,sst_cameroon_mean_temperature_deg_c_rollmin_14,sst_cameroon_mean_temperature_deg_c_rollmax_14,sst_cameroon_mean_temperature_deg_c_rollmean_30,sst_cameroon_mean_temperature_deg_c_rollmin_30,sst_cameroon_mean_temperature_deg_c_rollmax_30,sst_cameroon_mean_temperature_uncertainty_rollmean_7,sst_cameroon_mean_temperature_uncertainty_rollmin_7,sst_cameroon_mean_temperature_uncertainty_rollmax_7,sst_cameroon_mean_temperature_uncertainty_rollmean_14,sst_cameroon_mean_temperature_uncertainty_rollmin_14,sst_cameroon_mean_temperature_uncertainty_rollmax_14,sst_cameroon_mean_temperature_uncertainty_rollmean_30,sst_cameroon_mean_temperature_uncertainty_rollmin_30,sst_cameroon_mean_temperature_uncertainty_rollmax_30,sst_indian_ocean_mean_temperature_deg_c_rollmean_7,sst_indian_ocean_mean_temperature_deg_c_rollmin_7,sst_indian_ocean_mean_temperature_deg_c_rollmax_7,sst_indian_ocean_mean_temperature_deg_c_rollmean_14,sst_indian_ocean_mean_temperature_deg_c_rollmin_14,sst_indian_ocean_mean_temperature_deg_c_rollmax_14,sst_indian_ocean_mean_temperature_deg_c_rollmean_30,sst_indian_ocean_mean_temperature_deg_c_rollmin_30,sst_indian_ocean_mean_temperature_deg_c_rollmax_30,sst_indian_ocean_mean_temperature_uncertainty_rollmean_7,sst_indian_ocean_mean_temperature_uncertainty_rollmin_7,sst_indian_ocean_mean_temperature_uncertainty_rollmax_7,sst_indian_ocean_mean_temperature_uncertainty_rollmean_14,sst_indian_ocean_mean_temperature_uncertainty_rollmin_14,sst_indian_ocean_mean_temperature_uncertainty_rollmax_14,sst_indian_ocean_mean_temperature_uncertainty_rollmean_30,sst_indian_ocean_mean_temperature_uncertainty_rollmin_30,sst_indian_ocean_mean_temperature_uncertainty_rollmax_30,potential_water_deficit_rollmean_7,potential_water_deficit_rollmin_7,potential_water_deficit_rollmax_7,potential_water_deficit_rollmean_14,potential_water_deficit_rollmin_14,potential_water_deficit_rollmax_14,potential_water_deficit_rollmean_30,potential_water_deficit_rollmin_30,potential_water_deficit_rollmax_30,2m_temp_rollmean_7,2m_temp_rollmin_7,2m_temp_rollmax_7,2m_temp_rollmean_14,2m_temp_rollmin_14,2m_temp_rollmax_14,2m_temp_rollmean_30,2m_temp_rollmin_30,2m_temp_rollmax_30,u10_rollmean_7,u10_rollmin_7,u10_rollmax_7,u10_rollmean_14,u10_rollmin_14,u10_rollmax_14,u10_rollmean_30,u10_rollmin_30,u10_rollmax_30,vapor_pressure_deficit_rollmean_7,vapor_pressure_deficit_rollmin_7,vapor_pressure_deficit_rollmax_7,vapor_pressure_deficit_rollmean_14,vapor_pressure_deficit_rollmin_14,vapor_pressure_deficit_rollmax_14,vapor_pressure_deficit_rollmean_30,vapor_pressure_deficit_rollmin_30,vapor_pressure_deficit_rollmax_30,vapor_pressure_deficit_lag_1,vapor_pressure_deficit_lag_7,vapor_pressure_deficit_lag_14,vapor_pressure_deficit_diff_1,vapor_pressure_deficit_diff_7,5cm_soil_moist_lag_1,5cm_soil_moist_lag_7,5cm_soil_moist_lag_14,5cm_soil_moist_diff_1,5cm_soil_moist_diff_7,max_temp_lag_1,max_temp_lag_7,max_temp_lag_14,max_temp_diff_1,max_temp_diff_7,mean_dew_point_temp_lag_1,mean_dew_point_temp_lag_7,mean_dew_point_temp_lag_14,mean_dew_point_temp_diff_1,mean_dew_point_temp_diff_7,u10_lag_1,u10_lag_7,u10_lag_14,u10_diff_1,u10_diff_7,sea_level_pressure_lag_1,sea_level_pressure_lag_7,sea_level_pressure_lag_14,sea_level_pressure_diff_1,sea_level_pressure_diff_7,potential_water_deficit_lag_1,potential_water_deficit_lag_7,potential_water_deficit_lag_14,potential_water_deficit_diff_1,potential_water_deficit_diff_7,sst_cameroon_mean_temperature_deg_c_lag_1,sst_cameroon_mean_temperature_deg_c_lag_7,sst_cameroon_mean_temperature_deg_c_lag_14,sst_cameroon_mean_temperature_deg_c_diff_1,sst_cameroon_mean_temperature_deg_c_diff_7,sst_indian_ocean_mean_temperature_deg_c_lag_1,sst_indian_ocean_mean_temperature_deg_c_lag_7,sst_indian_ocean_mean_temperature_deg_c_lag_14,sst_indian_ocean_mean_temperature_deg_c_diff_1,sst_indian_ocean_mean_temperature_deg_c_diff_7
0,2002-07-30,0.26,21.19,32.71,101.03,25.48,0.23,28.10,0.16,2.48,26.74,-0.70,2.79,0,2002,7,2002,0.24,0.20,0.28,0.23,0.19,0.28,0.20,0.13,0.28,20.93,19.86,21.62,20.98,19.86,21.88,19.52,16.01,21.88,32.58,31.19,34.09,33.43,31.19,35.75,35.74,31.19,41.36,101.21,101.03,101.34,101.10,100.88,101.34,101.02,100.77,101.34,25.44,25.34,25.48,25.38,25.15,25.51,25.61,25.15,26.29,0.23,0.22,0.26,0.23,0.22,0.26,0.22,0.19,0.26,28.02,27.90,28.17,28.16,27.9,28.40,28.43,27.9,28.85,0.13,0.12,0.16,0.13,0.12,0.16,0.13,0.12,0.16,2.98,-3.11,8.11,1.26,-3.85,8.11,-2.93e-01,-4.61,8.11,27.01,26.31,27.84,27.60,26.31,29.11,29.39,26.31,33.59,0.09,-0.7,1.42,-6.27e-02,-1.45,1.42,0.48,-1.45,2.27,2.80,2.29,3.01,2.98,2.29,3.55,3.71,2.29,5.52,2.71,3.06,4.33,0.08,-0.27,0.25,0.21,0.24,2.20e-03,0.04,32.30,33.97,38.65,0.41,-1.25,21.62,21.35,19.42,-0.44,-0.16,0.86,-0.39,0.29,-1.56,-0.31,101.32,101.07,100.94,-0.30,-0.05,1.53,-1.54,-3.79,0.95,4.02,25.47,25.29,25.53,9.28e-03,1.92e-01,27.98,28.17,28.57,1.22e-01,-0.06
1,2002-07-31,0.22,19.07,32.39,100.99,25.48,0.24,27.98,0.15,2.68,27.04,0.44,2.94,0,2002,7,2002,0.24,0.20,0.28,0.23,0.19,0.28,0.20,0.13,0.28,20.64,19.07,21.62,20.88,19.07,21.88,19.62,16.01,21.88,32.47,31.19,34.09,33.39,31.19,35.75,35.48,31.19,41.36,101.19,100.99,101.34,101.10,100.88,101.34,101.02,100.77,101.34,25.46,25.41,25.48,25.37,25.15,25.48,25.59,25.15,26.29,0.23,0.22,0.24,0.23,0.22,0.26,0.22,0.19,0.26,28.00,27.90,28.17,28.14,27.9,28.34,28.40,27.9,28.85,0.14,0.12,0.16,0.13,0.12,0.16,0.13,0.12,0.16,2.54,-3.11,8.11,1.22,-3.85,8.11,-5.05e-02,-4.60,8.11,26.93,26.31,27.84,27.57,26.31,29.11,29.20,26.31,33.59,0.23,-0.7,1.42,5.71e-02,-1.45,1.42,0.47,-1.45,2.27,2.79,2.29,3.00,2.97,2.29,3.55,3.62,2.29,5.52,2.79,3.01,3.09,0.16,-0.06,0.26,0.21,0.20,-4.13e-02,0.01,32.71,33.16,32.94,-0.33,-0.78,21.19,21.14,20.42,-2.12,-2.07,-0.70,-0.54,-1.24,1.14,0.97,101.03,101.10,100.96,-0.04,-0.11,2.48,5.72,3.18,0.20,-3.04,25.48,25.34,25.51,1.68e-03,1.36e-01,28.10,28.12,28.40,-1.19e-01,-0.14
2,2002-08-01,0.22,20.12,35.32,101.00,25.41,0.23,27.99,0.12,-3.47,28.20,-0.31,3.44,0,2002,8,2002,0.24,0.22,0.28,0.23,0.19,0.28,0.20,0.13,0.28,20.68,19.07,21.62,20.84,19.07,21.88,19.73,16.01,21.88,32.92,31.19,35.32,33.42,31.19,35.75,35.28,31.19,40.47,101.16,100.99,101.34,101.10,100.88,101.34,101.03,100.77,101.34,25.46,25.41,25.48,25.37,25.15,25.48,25.57,25.15,26.29,0.23,0.22,0.24,0.23,0.22,0.26,0.22,0.20,0.26,27.98,27.90,28.10,28.11,27.9,28.33,28.37,27.9,28.82,0.13,0.12,0.16,0.13,0.12,0.16,0.13,0.12,0.16,1.19,-3.47,8.11,0.70,-3.85,8.11,-6.90e-02,-4.60,8.11,27.07,26.31,28.20,27.60,26.31,29.11,29.03,26.31,33.59,0.15,-0.7,1.42,-3.28e-02,-1.45,1.42,0.44,-1.45,2.27,2.88,2.29,3.44,2.98,2.29,3.55,3.55,2.29,5.15,2.94,2.85,3.28,0.50,0.59,0.22,0.20,0.21,3.40e-03,0.02,32.39,32.16,34.88,2.93,3.16,19.07,19.86,20.74,1.05,0.26,0.44,0.26,0.95,-0.75,-0.57,100.99,101.18,101.02,0.01,-0.19,2.68,6.02,3.81,-6.16,-9.49,25.48,25.41,25.41,-6.71e-02,6.57e-03,27.98,28.17,28.34,9.60e-03,-0.17
3,2002-08-02,0.25,20.61,32.69,101.16,25.34,0.31,27.96,0.12,1.43,26.81,0.74,2.69,0,2002,8,2002,0.24,0.22,0.26,0.24,0.20,0.28,0.21,0.13,0.28,20.73,19.07,21.62,20.84,19.07,21.88,19.76,16.01,21.88,32.96,31.19,35.32,33.42,31.19,35.75,35.10,31.19,40.47,101.14,100.99,101.34,101.10,100.88,101.34,101.03,100.77,101.34,25.45,25.34,25.48,25.37,25.15,25.48,25.54,25.15,26.29,0.24,0.22,0.31,0.24,0.22,0.31,0.23,0.20,0.31,27.98,27.90,28.10,28.08,27.9,28.32,28.34,27.9,28.79,0.13,0.12,0.16,0.13,0.12,0.16,0.13,0.12,0.16,1.38,-3.47,8.11,1.06,-3.85,8.11,-2.75e-01,-4.60,8.11,27.05,26.31,28.20,27.55,26.31,29.11,28.87,26.31,33.59,0.28,-0.7,1.42,1.16e-03,-1.45,1.42,0.41,-1.45,2.27,2.84,2.29,3.44,2.98,2.29,3.55,3.50,2.29,5.15,3.44,2.96,2.65,-0.75,-0.27,0.22,0.28,0.19,3.42e-02,-0.03,35.32,32.42,32.67,-2.63,0.27,20.12,20.25,20.48,0.49,0.36,-0.31,-0.15,0.27,1.05,0.89,101.00,101.29,101.11,0.16,-0.14,-3.47,0.08,-3.55,4.90,1.34,25.41,25.45,25.32,-7.21e-02,-1.04e-01,27.99,27.97,28.33,-3.64e-02,-0.02
4,2002-08-03,0.27,19.49,33.63,101.06,25.15,0.31,27.98,0.12,5.78,27.25,0.56,3.16,0,2002,8,2002,0.24,0.22,0.27,0.24,0.20,0.28,0.21,0.13,0.28,20.45,19.07,21.62,20.72,19.07,21.88,19.79,16.01,21.88,32.89,31.19,35.32,33.28,31.19,35.75,34.91,31.19,40.47,101.13,100.99,101.34,101.11,100.88,101.34,101.04,100.77,101.34,25.40,25.15,25.48,25.37,25.15,25.48,25.51,25.15,26.29,0.25,0.22,0.31,0.25,0.22,0.31,0.23,0.20,0.31,27.99,27.93,28.10,28.06,27.9,28.32,28.31,27.9,28.78,0.13,0.12,0.16,0.13,0.12,0.16,0.13,0.12,0.16,1.04,-3.47,5.78,1.58,-3.85,8.11,-5.42e-03,-4.60,8.11,26.97,26.31,28.20,27.42,26.31,29.08,28.69,26.31,33.59,0.43,-0.7,1.42,6.52e-02,-1.45,1.42,0.38,-1.45,2.27,2.86,2.29,3.44,2.97,2.29,3.55,3.45,2.29,5.15,2.69,3.00,3.30,0.47,0.16,0.25,0.25,0.26,2.12e-02,0.03,32.69,34.09,35.64,0.94,-0.46,20.61,21.42,21.17,-1.12,-1.93,0.74,-0.50,-0.34,-0.19,1.06,101.16,101.17,100.94,-0.10,-0.11,1.43,8.11,-1.53,4.35,-2.33,25.34,25.48,25.23,-1.89e-01,-3.31e-01,27.96,27.90,28.32,2.63e-02,0.08

In [60]:
test_df.head()

,date,5cm_soil_moist,mean_dew_point_temp,max_temp,sea_level_pressure,sst_cameroon_mean_temperature_deg_c,sst_cameroon_mean_temperature_uncertainty,sst_indian_ocean_mean_temperature_deg_c,sst_indian_ocean_mean_temperature_uncertainty,potential_water_deficit,2m_temp,u10,vapor_pressure_deficit,year,month,season_year,5cm_soil_moist_rollmean_7,5cm_soil_moist_rollmin_7,5cm_soil_moist_rollmax_7,5cm_soil_moist_rollmean_14,5cm_soil_moist_rollmin_14,5cm_soil_moist_rollmax_14,5cm_soil_moist_rollmean_30,5cm_soil_moist_rollmin_30,5cm_soil_moist_rollmax_30,mean_dew_point_temp_rollmean_7,mean_dew_point_temp_rollmin_7,mean_dew_point_temp_rollmax_7,mean_dew_point_temp_rollmean_14,mean_dew_point_temp_rollmin_14,mean_dew_point_temp_rollmax_14,mean_dew_point_temp_rollmean_30,mean_dew_point_temp_rollmin_30,mean_dew_point_temp_rollmax_30,max_temp_rollmean_7,max_temp_rollmin_7,max_temp_rollmax_7,max_temp_rollmean_14,max_temp_rollmin_14,max_temp_rollmax_14,max_temp_rollmean_30,max_temp_rollmin_30,max_temp_rollmax_30,sea_level_pressure_rollmean_7,sea_level_pressure_rollmin_7,sea_level_pressure_rollmax_7,sea_level_pressure_rollmean_14,sea_level_pressure_rollmin_14,sea_level_pressure_rollmax_14,sea_level_pressure_rollmean_30,sea_level_pressure_rollmin_30,sea_level_pressure_rollmax_30,sst_cameroon_mean_temperature_deg_c_rollmean_7,sst_cameroon_mean_temperature_deg_c_rollmin_7,sst_cameroon_mean_temperature_deg_c_rollmax_7,sst_cameroon_mean_temperature_deg_c_rollmean_14,sst_cameroon_mean_temperature_deg_c_rollmin_14,sst_cameroon_mean_temperature_deg_c_rollmax_14,sst_cameroon_mean_temperature_deg_c_rollmean_30,sst_cameroon_mean_temperature_deg_c_rollmin_30,sst_cameroon_mean_temperature_deg_c_rollmax_30,sst_cameroon_mean_temperature_uncertainty_rollmean_7,sst_cameroon_mean_temperature_uncertainty_rollmin_7,sst_cameroon_mean_temperature_uncertainty_rollmax_7,sst_cameroon_mean_temperature_uncertainty_rollmean_14,sst_cameroon_mean_temperature_uncertainty_rollmin_14,sst_cameroon_mean_temperature_uncertainty_rollmax_14,sst_cameroon_mean_temperature_uncertainty_rollmean_30,sst_cameroon_mean_temperature_uncertainty_rollmin_30,sst_cameroon_mean_temperature_uncertainty_rollmax_30,sst_indian_ocean_mean_temperature_deg_c_rollmean_7,sst_indian_ocean_mean_temperature_deg_c_rollmin_7,sst_indian_ocean_mean_temperature_deg_c_rollmax_7,sst_indian_ocean_mean_temperature_deg_c_rollmean_14,sst_indian_ocean_mean_temperature_deg_c_rollmin_14,sst_indian_ocean_mean_temperature_deg_c_rollmax_14,sst_indian_ocean_mean_temperature_deg_c_rollmean_30,sst_indian_ocean_mean_temperature_deg_c_rollmin_30,sst_indian_ocean_mean_temperature_deg_c_rollmax_30,sst_indian_ocean_mean_temperature_uncertainty_rollmean_7,sst_indian_ocean_mean_temperature_uncertainty_rollmin_7,sst_indian_ocean_mean_temperature_uncertainty_rollmax_7,sst_indian_ocean_mean_temperature_uncertainty_rollmean_14,sst_indian_ocean_mean_temperature_uncertainty_rollmin_14,sst_indian_ocean_mean_temperature_uncertainty_rollmax_14,sst_indian_ocean_mean_temperature_uncertainty_rollmean_30,sst_indian_ocean_mean_temperature_uncertainty_rollmin_30,sst_indian_ocean_mean_temperature_uncertainty_rollmax_30,potential_water_deficit_rollmean_7,potential_water_deficit_rollmin_7,potential_water_deficit_rollmax_7,potential_water_deficit_rollmean_14,potential_water_deficit_rollmin_14,potential_water_deficit_rollmax_14,potential_water_deficit_rollmean_30,potential_water_deficit_rollmin_30,potential_water_deficit_rollmax_30,2m_temp_rollmean_7,2m_temp_rollmin_7,2m_temp_rollmax_7,2m_temp_rollmean_14,2m_temp_rollmin_14,2m_temp_rollmax_14,2m_temp_rollmean_30,2m_temp_rollmin_30,2m_temp_rollmax_30,u10_rollmean_7,u10_rollmin_7,u10_rollmax_7,u10_rollmean_14,u10_rollmin_14,u10_rollmax_14,u10_rollmean_30,u10_rollmin_30,u10_rollmax_30,vapor_pressure_deficit_rollmean_7,vapor_pressure_deficit_rollmin_7,vapor_pressure_deficit_rollmax_7,vapor_pressure_deficit_rollmean_14,vapor_pressure_deficit_rollmin_14,vapor_pressure_deficit_rollmax_14,vapor_pressure_deficit_rollmean_30,vapor_pressure_deficit_rollmin_30,vapor_pressure_deficit_rollmax_30,vapor_pressure_deficit_lag_1,vapor_pressure_deficit_lag_7,vapor_pressure_deficit_lag_14,vapor_pressure_deficit_diff_1,vapor_pressure_deficit_diff_7,5cm_soil_moist_lag_1,5cm_soil_moist_lag_7,5cm_soil_moist_lag_14,5cm_soil_moist_diff_1,5cm_soil_moist_diff_7,max_temp_lag_1,max_temp_lag_7,max_temp_lag_14,max_temp_diff_1,max_temp_diff_7,mean_dew_point_temp_lag_1,mean_dew_point_temp_lag_7,mean_dew_point_temp_lag_14,mean_dew_point_temp_diff_1,mean_dew_point_temp_diff_7,u10_lag_1,u10_lag_7,u10_lag_14,u10_diff_1,u10_diff_7,sea_level_pressure_lag_1,sea_level_pressure_lag_7,sea_level_pressure_lag_14,sea_level_pressure_diff_1,sea_level_pressure_diff_7,potential_water_deficit_lag_1,potential_water_deficit_lag_7,potential_water_deficit_lag_14,potential_water_deficit_diff_1,potential_water_deficit_diff_7,sst_cameroon_mean_temperature_deg_c_lag_1,sst_cameroon_mean_temperature_deg_c_lag_7,sst_cameroon_mean_temperature_deg_c_lag_14,sst_cameroon_mean_temperature_deg_c_diff_1,sst_cameroon_mean_temperature_deg_c_diff_7,sst_indian_ocean_mean_temperature_deg_c_lag_1,sst_indian_ocean_mean_temperature_deg_c_lag_7,sst_indian_ocean_mean_temperature_deg_c_lag_14,sst_indian_ocean_mean_temperature_deg_c_diff_1,sst_indian_ocean_mean_temperature_deg_c_diff_7
0,2020-07-30,0.35,21.04,33.63,101.26,25.08,0.20,29.09,0.13,-3.51,26.83,-0.02,2.99,2020,7,2020,0.36,0.34,0.39,0.35,0.32,0.39,0.31,0.21,0.39,19.46,17.39,21.04,18.94,17.07,21.04,18.00,14.85,21.04,33.30,29.87,36.66,33.43,29.87,36.66,35.25,29.87,39.74,100.99,100.80,101.26,100.99,100.8,101.26,100.93,100.65,101.26,25.36,25.08,25.88,25.62,25.08,26.07,25.61,25.08,26.07,0.20,0.19,0.21,0.19,0.19,0.21,0.21,0.19,0.25,29.26,29.02,29.59,29.47,29.02,29.80,29.69,29.02,30.09,0.16,0.12,0.24,0.16,0.12,0.26,0.14,0.12,0.26,5.58,-3.51,21.38,5.19,-3.51,21.38,1.81,-4.79,21.38,27.53,25.20,30.07,27.71,25.20,30.07,29.28,25.20,32.77,0.60,-0.23,1.28,0.78,-0.23,1.51,1.05,-0.23,3.37,2.96,2.31,3.78,3.03,2.31,3.78,3.65,2.31,5.18,2.31,3.28,3.26,0.68,-0.29,0.36,0.36,0.30,-2.10e-03,-6.00e-03,29.87,34.54,35.43,3.76,-0.91,19.71,18.93,19.38,1.32,2.10,0.86,1.51,0.92,-0.88,-1.53,101.12,100.86,101.10,0.14,0.41,4.94,-0.16,5.10,-8.45,-3.35,25.10,26.02,25.28,-1.67e-02,-0.94,29.02,29.61,29.75,0.07,-0.52
1,2020-07-31,0.37,21.49,27.27,101.31,25.08,0.19,29.21,0.12,0.19,24.39,-0.81,1.43,2020,7,2020,0.36,0.35,0.39,0.35,0.32,0.39,0.31,0.21,0.39,20.05,18.70,21.49,19.19,17.07,21.49,18.17,14.85,21.49,31.96,27.27,34.93,32.87,27.27,36.66,34.85,27.27,39.74,101.06,100.85,101.31,101.01,100.8,101.31,100.95,100.65,101.31,25.25,25.08,25.68,25.58,25.08,26.07,25.60,25.08,26.07,0.20,0.19,0.21,0.19,0.19,0.21,0.21,0.19,0.25,29.20,29.02,29.58,29.43,29.02,29.79,29.66,29.02,30.09,0.16,0.12,0.24,0.16,0.12,0.26,0.14,0.12,0.26,5.49,-3.51,21.38,4.60,-3.51,21.38,1.95,-4.79,21.38,26.72,24.39,29.00,27.43,24.39,30.07,29.02,24.39,32.77,0.37,-0.81,1.28,0.63,-0.81,1.51,0.92,-0.81,3.37,2.62,1.43,3.32,2.90,1.43,3.78,3.53,1.43,5.18,2.99,3.78,3.20,-1.56,-2.36,0.35,0.34,0.37,1.82e-02,3.69e-02,33.63,36.66,35.11,-6.36,-9.38,21.04,17.39,18.03,0.45,4.10,-0.02,0.76,1.29,-0.79,-1.57,101.26,100.80,101.09,0.05,0.51,-3.51,0.79,8.43,3.70,-0.60,25.08,25.88,25.56,1.03e-03,-0.80,29.09,29.59,29.80,0.12,-0.38
2,2020-08-01,0.37,19.59,27.30,101.15,25.33,0.20,29.23,0.12,3.42,23.47,-0.59,1.95,2020,8,2020,0.37,0.35,0.39,0.35,0.32,0.39,0.32,0.21,0.39,20.11,18.70,21.49,19.26,17.07,21.49,18.21,14.85,21.49,31.05,27.27,34.93,32.37,27.27,36.66,34.53,27.27,39.74,101.10,100.88,101.31,101.02,100.8,101.31,100.97,100.65,101.31,25.20,25.08,25.47,25.56,25.08,26.07,25.59,25.08,26.07,0.20,0.19,0.20,0.19,0.19,0.21,0.21,0.19,0.25,29.15,29.02,29.40,29.39,29.02,29.76,29.63,29.02,30.07,0.15,0.12,0.24,0.16,0.12,0.26,0.14,0.12,0.26,4.37,-3.51,21.38,4.34,-3.51,21.38,2.18,-4.79,21.38,26.03,23.47,29.00,27.11,23.47,30.07,28.76,23.47,32.77,0.15,-0.81,1.28,0.52,-0.81,1.51,0.79,-0.81,2.18,2.49,1.43,3.32,2.80,1.43,3.78,3.46,1.43,5.18,1.43,2.90,3.27,0.52,-0.96,0.37,0.35,0.35,1.40e-03,2.27e-02,27.27,33.65,34.28,0.03,-6.35,21.49,19.18,18.50,-1.90,0.41,-0.81,0.98,0.93,0.22,-1.57,101.31,100.85,100.96,-0.16,0.29,0.19,11.22,7.03,3.23,-7.80,25.08,25.68,25.69,2.51e-01,-0.35,29.21,29.58,29.79,0.02,-0.35
3,2020-08-02,0.36,20.25,30.53,101.18,25.42,0.19,29.15,0.13,0.30,26.27,-0.72,2.63,2020,8,2020,0.37,0.35,0.39,0.35,0.32,0.39,0.32,0.21,0.39,20.33,19.59,21.49,19.41,17.07,21.49,18.34,14.85,21.49,30.42,27.27,33.63,32.26,27.27,36.66,34.31,27.27,39.74,101.13,100.88,101.31,101.03,100.8,101.31,100.98,100.65,101.31,25.19,25.08,25.42,25.54,25.08,26.07,25.59,25.08,26.07,0.20,0.19,0.20,0.20,0.19,0.21,0.21,0.19,0.25,29.12,29.02,29.23,29.34,29.02,29.61,29.60,29.02,30.03,0.14,0.12,0.15,0.15,0.12,0.24,0.14,0.12,0.26,4.60,-3.51,21.38,3.15,-3.51,21.38,2.35,-3.89,21.38,25.64,23.47,26.83,27.03,23.47,30.07,28.61,23.47,32.77,-0.14,-0.81,0.86,0.37,-0.81,1.51,0.72,-0.81,2.18,2.39,1.43,2.99,2.79,1.43,3.78,3.40,1.43,5.18,1.95,3.32,2.88,0.68,-0.69,0.37,0.36,0.36,-1.83e-02,-5.90e-03,27.30,34.93,32.04,3.23,-4.41,19.59,18.70,18.18,0.66,1.55,-0.59,1.28,1.34,-0.13,-2.00,101.15,100.98,101.07,0.03,0.20,3.42,-1.27,16.96,-3.12,1.57,25.33,25.47,25.75,8.89e-02,-0.05,29.23,29.40,29.76,-0.08,-0.25
4,2020-08-03,0.35,21.27,29.06,101.34,25.46,0.19,29.00,0.12,-2.39,25.72,-0.04,1.83,2020,8,2020,0.36,0.35,0.37,0.36,0.32,0.39,0.33,0.21,0.39,20.53,19.59,21.49,19.71,17.39,21.49,18.51,14.85,21.49,30.01,27.27,33.63,31.84,27.27,36.66,33.97,27.27,39.74,101.18,100.88,101.34,101.04,100.8,101.34,100.99,100.65,101.34,25.23,25.08,25.46,25.50,25.08,26.07,25.58,25.08,26.07,0.19,0.19,0.20,0.20,0.19,0.21,0.21,0.19,0.25,29.11,29.00,29.23,29.30,29.00,29.61,29.56,29.00,29.95,0.13,0.12,0.15,0.14,0.12,0.24,0.14,0.12,0.26,3.48,-3.51,21.38,3.20,-3.51,21.38,2.31,-3.89,21.38,25.49,23.47,26.83,26.83,23.47,30.07,28.40,23.47,32.77,-0.22,-0.81,0.86,0.28,-0.81,1.51,0.67,-0.81,2.18,2.28,1.43,2.99,2.66,1.43,3.78,3.29,1.43,5.18,2.63,2.59,3.54,-0.80,-0.76,0.36,0.39,0.34,-1.10e-03,-3.41e-02,30.53,31.92,34.99,-1.46,-2.85,20.25,19.86,17.07,1.02,1.41,-0.72,0.57,1.32,0.68,-0.61,101.18,101.04,101.18,0.16,0.30,0.30,5.48,-3.01,-2.68,-7.87,25.42,25.20,25.98,4.21e-02,0.27,29.15,29.05,29.57,-0.15,-0.05

In [61]:
target_col = "dryspell_warn_7d"

drop_cols = ["date", "season_year", target_col]

if "year" in train_df.columns:
    drop_cols.append("year")

feature_cols = [col for col in train_df.columns if col not in drop_cols]
print("Number of features:", len(feature_cols))
print(feature_cols[:20])

Number of features: 166
['5cm_soil_moist', 'mean_dew_point_temp', 'max_temp', 'sea_level_pressure', 'sst_cameroon_mean_temperature_deg_c', 'sst_cameroon_mean_temperature_uncertainty', 'sst_indian_ocean_mean_temperature_deg_c', 'sst_indian_ocean_mean_temperature_uncertainty', 'potential_water_deficit', '2m_temp', 'u10', 'vapor_pressure_deficit', 'month', '5cm_soil_moist_rollmean_7', '5cm_soil_moist_rollmin_7', '5cm_soil_moist_rollmax_7', '5cm_soil_moist_rollmean_14', '5cm_soil_moist_rollmin_14', '5cm_soil_moist_rollmax_14', '5cm_soil_moist_rollmean_30']

In [62]:
train_mask =train_df["season_year"]<= 2016
val_mask =train_df["season_year"]>= 2017

train_part = train_df.loc[train_mask].copy()
val_part = train_df.loc[val_mask].copy()

X_train = train_part[feature_cols]
y_train = train_part[target_col]

X_val = val_part[feature_cols]
y_val = val_part[target_col]

print("Train seasons:", sorted(train_part["season_year"].unique()))
print("Validation seasons:", sorted(val_part["season_year"].unique()))
print("X_train shape:", X_train.shape)
print("X_val shape:", X_val.shape)

Train seasons: [np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016)]
Validation seasons: [np.int64(2017), np.int64(2018), np.int64(2019)]
X_train shape: (1410, 166)
X_val shape: (282, 166)

In [65]:
models = {
    "logreg":Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(
            class_weight="balanced",
            max_iter=2000,
            random_state=42
        ))
    ]),
    "random_forest": RandomForestClassifier(
        n_estimators=300,
        max_depth=None,
        min_samples_leaf=2,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    ),

    "hist_gb": HistGradientBoostingClassifier(
        learning_rate=0.05,
        max_depth=6,
        max_iter= 300,
        random_state=42
    )
}

In [66]:
def evaluate_model(name, model, X_train, y_train, X_val, y_val):
    # Fit
    if name == "hist_gb":
        # Approx balanced sample weights
        class_counts = y_train.value_counts()
        w0 = 1.0
        w1 = class_counts[0] / class_counts[1]
        sample_weight = y_train.map({0: w0, 1: w1})
        model.fit(X_train, y_train, sample_weight=sample_weight)
    else:
        model.fit(X_train, y_train)
    # Predict proba
    if hasattr(model, "predict_proba"):
        val_probs = model.predict_proba(X_val)[:, 1]
    else:
        # fallback for models without predict_proba
        val_probs = model.decision_function(X_val)
    # Find best threshold by F1
    precision, recall, thresholds = precision_recall_curve(y_val, val_probs)
    f1_scores = (2 * precision * recall) / (precision + recall + 1e-9)
    best_idx = np.argmax(f1_scores)
    best_threshold = thresholds[best_idx] if best_idx < len(thresholds) else 0.5
    val_pred = (val_probs >= best_threshold).astype(int)
    metrics = {
        "model": name,
        "best_threshold": best_threshold,
        "f1": f1_score(y_val, val_pred),
        "precision": precision_score(y_val, val_pred),
        "recall": recall_score(y_val, val_pred),
        "confusion": confusion_matrix(y_val, val_pred)
    }
    return metrics, val_probs

In [68]:
results = []
for name, model in models.items():
    metrics, _ = evaluate_model(name, model, X_train, y_train, X_val, y_val)
    results.append(metrics)
results_df = pd.DataFrame([
    {k: v for k, v in r.items() if k != "confusion"} for r in results
]).sort_values("f1", ascending=False)
print(results_df)
for r in results:
    print(f"\n{r['model']} confusion matrix:")
    print(r["confusion"])

           model  best_threshold    f1  precision  recall
1  random_forest            0.15  0.48       0.32    1.00
2        hist_gb            0.02  0.41       0.27    0.86
0         logreg            0.02  0.34       0.22    0.71

logreg confusion matrix:
[[185  69]
 [  8  20]]

random_forest confusion matrix:
[[194  60]
 [  0  28]]

hist_gb confusion matrix:
[[189  65]
 [  4  24]]

In [71]:
# Refit best model on full training data
best_threshold = 0.15

X_full = train_df[feature_cols]
y_full = train_df[target_col]
best_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_leaf=2,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)
best_model.fit(X_full, y_full)
# Predict on test
X_test = test_df[feature_cols]
test_probs = best_model.predict_proba(X_test)[:, 1]
test_pred = (test_probs >= best_threshold).astype(int)
pred_df = pd.DataFrame({
    "date": test_df["date"],
    "prob_dryspell": test_probs,
    "pred_label": test_pred
})
pred_df.to_csv("../data/processed/test_predictions.csv", index=False)
pred_df.head()

        date  prob_dryspell  pred_label
0 2020-07-30       5.39e-03           0
1 2020-07-31       5.39e-03           0
2 2020-08-01       2.70e-03           0
3 2020-08-02       4.64e-03           0
4 2020-08-03       6.03e-03           0

In [72]:
pred_df["pred_label"].mean()
pred_df["prob_dryspell"].describe()

count    564.00
mean       0.08
std        0.09
min        0.00
25%        0.02
50%        0.05
75%        0.13
max        0.57
Name: prob_dryspell, dtype: float64